# Generated by Django 3.0.6 on 2020-05-08 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import goodHealthApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(default=True)),
                ('media1', models.FileField(upload_to=goodHealthApp.models.get_upload_path)),
                ('media2', models.FileField(blank=True, null=True, upload_to=goodHealthApp.models.get_upload_path)),
                ('media3', models.FileField(blank=True, null=True, upload_to=goodHealthApp.models.get_upload_path)),
                ('location', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodHealthApp.UserProfile')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
