# Generated by Django 2.2.7 on 2020-05-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='extra',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
