# Generated by Django 3.0.6 on 2020-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodHealthApp', '0002_auto_20200509_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
