# Generated by Django 3.0.6 on 2020-05-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodHealthApp', '0003_emergencyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyline',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
